"""wechat

Revision ID: 5f25420bd585
Revises: b9c28717229a
Create Date: 2025-09-08 16:21:27.962278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f25420bd585'
down_revision: Union[str, Sequence[str], None] = 'b9c28717229a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='chatroom'
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=200), nullable=False),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    schema='wechat'
    )
    op.create_index(op.f('ix_wechat_oauth_tokens_id'), 'oauth_tokens', ['id'], unique=False, schema='wechat')
    op.create_table('payment_notifies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('result_code', sa.String(length=16), nullable=False),
    sa.Column('return_code', sa.String(length=16), nullable=False),
    sa.Column('notify_data', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='wechat'
    )
    op.create_index(op.f('ix_wechat_payment_notifies_id'), 'payment_notifies', ['id'], unique=False, schema='wechat')
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('attach', sa.String(length=127), nullable=True),
    sa.Column('trade_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('prepay_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('out_trade_no'),
    schema='wechat'
    )
    op.create_index(op.f('ix_wechat_payment_orders_id'), 'payment_orders', ['id'], unique=False, schema='wechat')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='wechat'
    )
    op.create_index(op.f('ix_wechat_users_id'), 'users', ['id'], unique=False, schema='wechat')
    op.create_index(op.f('ix_wechat_users_openid'), 'users', ['openid'], unique=True, schema='wechat')
    op.create_index(op.f('ix_wechat_users_unionid'), 'users', ['unionid'], unique=True, schema='wechat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wechat_users_unionid'), table_name='users', schema='wechat')
    op.drop_index(op.f('ix_wechat_users_openid'), table_name='users', schema='wechat')
    op.drop_index(op.f('ix_wechat_users_id'), table_name='users', schema='wechat')
    op.drop_table('users', schema='wechat')
    op.drop_index(op.f('ix_wechat_payment_orders_id'), table_name='payment_orders', schema='wechat')
    op.drop_table('payment_orders', schema='wechat')
    op.drop_index(op.f('ix_wechat_payment_notifies_id'), table_name='payment_notifies', schema='wechat')
    op.drop_table('payment_notifies', schema='wechat')
    op.drop_index(op.f('ix_wechat_oauth_tokens_id'), table_name='oauth_tokens', schema='wechat')
    op.drop_table('oauth_tokens', schema='wechat')
    op.drop_table('user', schema='chatroom')
    # ### end Alembic commands ###
